### ISSUE TITLE
背景插件已支持不启用前景透明

### ISSUE THREAD

**Issue by HowcanoeWang** [chenshinshi/Cliff-Dark#1]
可以用来当这个主题的背景图片管理器了，不需要手动替换背景图片

![image](https://github.com/chenshinshi/Cliff-Dark/assets/19968935/724c9cef-9b51-4dfc-8375-c63a47fc76c0)

https://github.com/HowcanoeWang/siyuan-plugin-background-cover/releases/tag/0.4.5

**Comment by HowcanoeWang** [comment]
就是按钮最好能加个白色描边，不然部分背景下看不太清

![image](https://github.com/chenshinshi/Cliff-Dark/assets/19968935/f233be72-0de5-4560-a0af-0604ef87013f)
![image](https://github.com/chenshinshi/Cliff-Dark/assets/19968935/7cd210fa-a27c-4f78-b032-ac440d452929)

**Comment by chenshinshi** [comment]
感谢适配，新版本已修改侧栏图标样式！
