### ISSUE TITLE
关于作者信息

### ISSUE THREAD

**Issue by Crowds21** [chenshinshi/Cliff-Dark#11]
感谢老哥能够继续维护, 并在 RAMDE 文件中提及到我, 作者信息修改成你自己就好.
比心!

**Comment by chenshinshi** [comment]
啊啊啊啊啊是原作者！感谢老哥制作的主题！您的主题的设计还启发了现在在思源特别火的另外一款主题。我反而是修的更垃圾了。最近两个月忙于工作没有怎么更新，看到您的回复实在太高兴了！比心！
