### ISSUE TITLE
3.3.5版本代码块行号错乱

### ISSUE THREAD

**Issue by emptylight370** [chenshinshi/Cliff-Dark#5]
在新版思源(2.10.13)中出现代码块行号错乱现象，通过切换主题发现使用Cliff-Dark主题时会出现这种情况，表现为代码块行号向下偏移约1.5行高度，代码块元素高度增加。
#### 屏幕截图
![image](https://github.com/chenshinshi/Cliff-Dark/assets/61617417/acb59e3c-215f-41ae-ba58-8524f470e83d)

**Comment by chenshinshi** [comment]
收到，近期会处理。
