### ISSUE TITLE
窗口拖动不支持

### ISSUE THREAD

**Issue by luommy** [chenshinshi/Cliff-Dark#9]
小窗口下目前好像不支持拖动，请问能否支持适配?
![image](https://github.com/chenshinshi/Cliff-Dark/assets/72240631/f7e8c5e7-1d53-495c-a3e7-690c87caba64)

**Comment by chenshinshi** [comment]
不能通过计数器移动吗？你看下readme

**Comment by chenshinshi** [comment]
不能通过计数器移动吗？你看下readme

**Comment by chenshinshi** [comment]
https://github.com/chenshinshi/Cliff-Dark/assets/125173405/ac1d7a4e-0b0b-439f-82d0-cb1cbb617b81
